version: '3.7'

services:
  db:
    image: postgres
    env_file:
      - ./config/.env
    volumes:
      - sheepfish_postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - '8080:80'

volumes:
  sheepfish_postgres_data:
