# Generated by Django 4.2.4 on 2023-09-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("printers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("client", "Client")],
                        max_length=7,
                        verbose_name="Check type",
                    ),
                ),
                ("order", models.JSONField(verbose_name="Information about order")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("rendered", "Rendered"),
                            ("printed", "Printed"),
                        ],
                        default="new",
                        max_length=8,
                        verbose_name="Check status",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Check-PDF file",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="printers.printer",
                        verbose_name="Printer",
                    ),
                ),
            ],
        ),
    ]
