# Generated by Django 4.2.4 on 2023-09-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Printer name")),
                ("api_key", models.CharField(max_length=50, verbose_name="API key")),
                (
                    "check_type",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("client", "Client")],
                        max_length=7,
                        verbose_name="Check type",
                    ),
                ),
                (
                    "point_id",
                    models.IntegerField(
                        verbose_name="Point to which the printer is bound"
                    ),
                ),
            ],
        ),
    ]
