# Generated by Django 4.2.4 on 2023-09-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="api_key",
            field=models.CharField(max_length=50, unique=True, verbose_name="API key"),
        ),
    ]
