# Generated by Django 4.2.4 on 2023-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printers", "0002_alter_printer_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="api_key",
            field=models.CharField(max_length=35, unique=True, verbose_name="API key"),
        ),
    ]
